{
    'name': 'Bizapps - VN Address NQ60',
    'version': '1.0',
    'summary': 'Thay đổi địa chỉ Việt Nam theo NQ60',
    "author": "support@bizapps.vn",
    "website": "https://bizapps.vn/ung-dung",
    'category': 'Base',
    'depends': ['base', 'biz_vn_address'],
    'data': [
        'security/ir.model.access.csv',
        'data/data_import.xml',
        'data/ir_filters.xml',
        'data/res_country_state.xml',
        'views/import_wards_view.xml',
        'views/res_country.xml',
        'views/res_partner_view.xml',
        'views/res_company_view.xml',
        'views/menu.xml',
    ],
    'installable': True,
    'application': False,
    'license': 'OPL-1',
    'post_init_hook': 'do_merge_state',
}